name: Release
on:
    push:
        branches:
            - "main"
    workflow_dispatch:

jobs:
    publish_windows:
        name: "Publish Windows"
        runs-on: windows-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Install Node.js and NPM
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            - name: Install dependencies
              # npm ci is better, but requires package-lock.json file
              run: npm install

            - name: Build app
              run: npm run build

            - name: Build and release app
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
                  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
                  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
              run: |
                  if [ -n "${AZURE_TENANT_ID}" ] && [ -n "${AZURE_CLIENT_ID}" ] && [ -n "${AZURE_CLIENT_SECRET}" ]; then
                    npm run release
                  else
                    npm run release:internal
                  fi
              shell: bash

    publish_mac:
        name: "Publish MacOS"
        runs-on: macos-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Install Node.js and NPM
              uses: actions/setup-node@v4
              with:
                  node-version: 22

            # Change Python version: https://github.com/nodejs/node-gyp/issues/2869
            - name: Install Python 3.11
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            # This probably does not make any difference.
            - name: Install node-gyp
              run: npm install -g node-gyp

            - name: Install dependencies
              run: npm install

            - name: Install dmg-license
              run: npm i dmg-license

            - name: Build app
              run: npm run build

            # for some reason the build command don't continue after the rollup build
            - name: Sleep for 3 minutes
              run: sleep 180
              shell: bash

            - name: Build and release app
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CSC_LINK: ${{ secrets.CSC_LINK }}
                  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
                  APPLE_ID: ${{ secrets.APPLEID }}
                  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
                  APPLE_TEAM_ID: ${{ secrets.APPLETEAMID }}
              run: |
                  if [ -n "${CSC_LINK}" ] && [ -n "${CSC_KEY_PASSWORD}" ] && [ -n "${APPLE_ID}" ] && [ -n "${APPLE_APP_SPECIFIC_PASSWORD}" ] && [ -n "${APPLE_TEAM_ID}" ]; then
                    npm run release
                  else
                    npm run release:internal
                  fi
              shell: bash
